baseURL = 'https://tab.4x.re/'
languageCode = 'en-us'
title = 'The Holy Order of Tab'

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 5
  showLanguageSelector = true
  fullWidthTheme = false
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  readingTime = false

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"
[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    title = "The Holy Order of Tab"

    [languages.en.params]
      subtitle = "Our mission is to guide terminal users toward a brighter, more efficient future by spreading the gospel of autocomplete and reducing the burden of unnecessary keystrokes."
      owner = ""
      keywords = "tab"
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "The Holy Order of Tab"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/posts/about"
        [[languages.en.menu.main]]
          identifier = "manifesto"
          name = "Manifesto"
          url = "/posts/manifesto"
        [[languages.en.menu.main]]
          identifier = "tabulay"
          name = "TabULay Layout"
          url = "/posts/tabulay"
        [[languages.en.menu.main]]
          identifier = "badge"
          name = "Get A Badge"
          url = "/posts/badge"
        [[languages.en.menu.main]]
          identifier = "why"
          name = "Why ??"
          url = "/posts/why"
  [languages.fr]
    weight = 2
    languageName = "Français"
    title = "Ordre du Saint Tab"
    [languages.fr.params]
      subtitle = "Notre mission est de guider les utilisateurs de terminaux vers un avenir plus lumineux et efficace en diffusant l'art de l'autocomplétion et en réduisant la charge des frappes inutiles."
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Afficher plus"
      readMore = "Lire la suite"
      readOtherPosts = "Voir d'autres articles"
      newerPosts = "Articles plus récents"
      olderPosts = "Articles plus anciens"
      missingContentMessage = "Page introuvable..."
      missingBackButtonLabel = "Retour à la page d'accueil"
    [languages.fr.params.logo]
      logoText = "Ordre du Saint Tab"
      logoHomeLink = "/fr/"
  [languages.fr.menu]
    [[languages.fr.menu.main]]
      weight = 1
      identifier = "about"
      name = "À propos"
      url = "/fr/posts/about"
    [[languages.fr.menu.main]]
      weight = 2
      identifier = "badge"
      name = "Obtenir un badge"
      url = "/fr/posts/badge"
    [[languages.fr.menu.main]]
      weight = 3
      identifier = "manifesto"
      name = "Manifeste"
      url = "/fr/posts/manifesto"
    [[languages.fr.menu.main]]
      weight = 4
      identifier = "tabulay"
      name = "Clavier TabULay"
      url = "/fr/posts/tabulay"
    [[languages.fr.menu.main]]
      weight = 5
      identifier = "why"
      name = "Pourquoi ??"
      url = "/fr/posts/why"

[module]
[[module.imports]]
  path = 'github.com/panr/hugo-theme-terminal/v4'